### ISSUE TITLE
requesting advice re jpeg output black

### ISSUE THREAD

**Issue by linuxgirl22** [alexandervrs/SAI-Autosave#1]
Hello :-) I realise this plugin is written for Windows, but I tried running it on Linux (endeavourOS and Mate, running Sai2 portable) and it's the only one that actually runs, sets things up, and also saves snapshots, which is awesome work! The only issue I have is that the jpeg snapshots are black. If you could point me in the right direction about what this could be caused by, I'd be very grateful.

**Comment by alexandervrs** [comment]
Hello! This actually sounds like a security issue, since I *believe* the autosave program captures the entire screen, it might capture something outside the SAI window at times & the OS might not really permit that unless the program is run with elevated privileges (run as admin).

**Comment by linuxgirl22** [comment]
Hello! Thank you very much for your response. I'm running Sai2 via Wine, which runs things contained within Wine itself, allowing no access to root/linux system files. That's where my knowledge about Wine pretty much ends, lol, so your idea sounds awesome and very much like it would work. Really appreciate.

**Comment by alexandervrs** [comment]
Actually I noticed I am already using _ScreenCapture_CaptureWnd() to capture the SAI window and then _ScreenCapture_SaveImage() to save the image to disk, so I am actually not grabbing the whole screen. 

However I tried a method with a modified _ScreenCapture_CaptureWnd() which uses GDI interface to capture the image. I cannot build an .exe though because the script requires AutoIt 3.3, and trying to build an .exe with it right now results in a false positive with Windows Defender for some reason.

Not sure if it will work differently as I cannot test it myself at the moment, but I did a commit if you want to try it out, you just need AutoIt 3.3 to compile the .exe.

**Comment by DeenOConnor** [comment]
You should check if wine supports that at all, since it's a compatibility layer, and some of WinAPI functions might not be implemented.
Btw i checked with winetricks, i believe that GDI support comes as a separate package that you need to install manually.

**Comment by linuxgirl22** [comment]
Hello @alexandervrs and @DeenOConnor ... and sincere apologies for delay in replying. I'm using Linux, but now Linux Mint Mate 20.2, so just checked out the autosave 3 that has the exe, with using a different distro, and seeing jpegs are black. Used to install gdiplus, I think when running CSP way back when, so will give it a go. Thanks!

**Comment by linuxgirl22** [comment]
Just to report winetricks gdiplus didn't fix the jpegs issue unfortunately. I don't want to add extra windows stuff, and am not anywhere near building exe files anyway, eek, so will leave it for now.

**Comment by alexandervrs** [comment]
I wonder if it's some incompatibility or unsupported feature of Wine in the end. 
It's okay, I'll close this for now but might look into this again in the future if I install Linux myself.
